export const initialTeams = [
  {
    name: 'Les Avengers',
    members: ['Malo', 'Romain', 'Eliah', 'Margot', 'Mathis'],
    batteryLevel: 76,
    color: 'orange',
    hat: 'headset',
    isOutside: false,
    latitude: 45.90053,
    longitude: 6.1284,
    score: 0,
  },
  {
    name: 'Les cœurs de lions',
    members: ['Lou', 'Elina', 'Gabriel', 'Camille', 'Alyssa'],
    batteryLevel: 45,
    color: 'pink',
    hat: 'cook',
    isOutside: false,
    latitude: 45.9006,
    longitude: 6.12836,
    score: 0,
  },
  {
    name: 'Les déter-gens',
    members: ['Carolie', 'Maelys', 'Clément', 'Lucie', 'Léo'],
    batteryLevel: 92,
    color: 'skyblue',
    hat: 'propeller',
    isOutside: false,
    latitude: 45.90062,
    longitude: 6.1284,
    score: 0,
  },
  {
    name: 'Les snippers',
    members: ['Lilou', 'Violette', 'Jules', 'Lilian', 'Louis'],
    batteryLevel: 71,
    color: 'violet',
    hat: 'bonnet',
    isOutside: false,
    latitude: 45.900562,
    longitude: 6.12836,
    score: 0,
  },
]
