
APP_ID = "fr.journiz.app"
PROVISIONING_PROFILE_APPSTORE = "match AppStore fr.journiz.app"
TEAM_ID = "54PCF2T5ZE"

settings_to_override_release = { 
  :BUNDLE_IDENTIFIER => APP_ID, 
  :PROVISIONING_PROFILE_SPECIFIER => PROVISIONING_PROFILE_APPSTORE, 
  :DEVELOPMENT_TEAM => TEAM_ID, 
}

desc "Export IPA & upload to TestFlight"
lane :upload_testflight do
  api_key = app_store_connect_api_key(
    key_id: $APP_STORE_CONNECT_API_KEY_KEY_ID,
    issuer_id: $APP_STORE_CONNECT_API_KEY_ISSUER_ID,
    key_content: $APP_STORE_CONNECT_API_KEY_KEY
  )
  increment_build_number(
        build_number: latest_testflight_build_number(
          api_key: api_key,
          initial_build_number: 1,
          version: get_version_number(xcodeproj: "App.xcodeproj")
        ) + 1,
  )
  match(type: "appstore")
  gym(scheme: "App")

end