
APP_ID = "fr.journiz.app"
PROVISIONING_PROFILE_APPSTORE = "match AppStore fr.journiz.app"
TEAM_ID = "54PCF2T5ZE"

settings_to_override_release = { 
  :BUNDLE_IDENTIFIER => APP_ID, 
  :PROVISIONING_PROFILE_SPECIFIER => PROVISIONING_PROFILE_APPSTORE, 
  :DEVELOPMENT_TEAM => TEAM_ID,
  :CODE_SIGN_STYLE => "Manual",
}

desc "Export IPA & upload to TestFlight"
lane :upload_testflight do
  api_key = app_store_connect_api_key(
    key_id: $APP_STORE_CONNECT_API_KEY_KEY_ID,
    issuer_id: $APP_STORE_CONNECT_API_KEY_ISSUER_ID,
    key_content: $APP_STORE_CONNECT_API_KEY_KEY
  )
  increment_build_number(
        build_number: latest_testflight_build_number(
          api_key: api_key,
          initial_build_number: 1,
          version: get_version_number(xcodeproj: "App.xcodeproj")
        ) + 1,
  )
  match(
    app_identifier: APP_ID,
    readonly: is_ci,
    type: "adhoc"
  )
  build_app(
      scheme:"App",
      export_method:"ad-hoc",
      skip_profile_detection:true,
      configuration: "Release",
      workspace: "App.xcworkspace",
      xcargs: settings_to_override_release,
      export_options: {
        provisioningProfiles: {
          APP_ID => PROVISIONING_PROFILE_APPSTORE
        },
        # installerSigningCertificate: "your_installer_signing_certificate_name"
      }
    )

end