# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build APK"
  lane :build do
      gradle(
          task: "assemble",
          build_type: "Release",
          properties: {
            "android.injected.signing.store.file" => "/Users/ponk/tmp.jks",
            "android.injected.signing.store.password" => "journiz",
            "android.injected.signing.key.alias" => "key0",
            "android.injected.signing.key.password" => "journiz",
          }
      )
  end
end
