# .circleci/config.yml
version: 2.1
jobs:
  testflight:
    working_directory: ~/journiz/app/ios/App
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: upload_testflight
    steps:
      - checkout:
          path: ~/journiz
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run: bundle install
      - run: gem install cocoapods
      - run: pnpm dlx @capacitor/cli cap sync ios
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output


workflows:
  app-staging:
    jobs:
      - testflight:
          filters:
            branches:
              only: chore/ci
