# .circleci/config.yml
version: 2.1
orbs:
  cocoapods: dantoml/cocoapods@0.0.2
jobs:
  testflight:
    working_directory: ~/journiz/app/ios/App
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: upload_testflight
    steps:
      - checkout:
          path: ~/journiz
      - run: bundle install
      - cocoapods/fetch-specs
      - cocoapods/install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output


workflows:
  app-staging:
    jobs:
      - testflight:
          filters:
            branches:
              only: chore/ci
