require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/.pnpm/@capacitor+ios@5.0.3_@capacitor+core@5.0.3/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/.pnpm/@capacitor+ios@5.0.3_@capacitor+core@5.0.3/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityBackgroundGeolocation', :path => '../../../node_modules/.pnpm/@capacitor-community+background-geolocation@1.2.14_@capacitor+core@5.0.3/node_modules/@capacitor-community/background-geolocation'
  pod 'CapacitorApp', :path => '../../../node_modules/.pnpm/@capacitor+app@5.0.2_@capacitor+core@5.0.3/node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../../node_modules/.pnpm/@capacitor+camera@5.0.2_@capacitor+core@5.0.3/node_modules/@capacitor/camera'
  pod 'CapacitorDialog', :path => '../../../node_modules/.pnpm/@capacitor+dialog@5.0.2_@capacitor+core@5.0.3/node_modules/@capacitor/dialog'
  pod 'CapacitorHaptics', :path => '../../../node_modules/.pnpm/@capacitor+haptics@5.0.2_@capacitor+core@5.0.3/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../node_modules/.pnpm/@capacitor+keyboard@5.0.2_@capacitor+core@5.0.3/node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/.pnpm/@capacitor+status-bar@5.0.2_@capacitor+core@5.0.3/node_modules/@capacitor/status-bar'
  pod 'CapacitorNativeSettings', :path => '../../../node_modules/.pnpm/capacitor-native-settings@5.0.0_@capacitor+core@5.0.3/node_modules/capacitor-native-settings'
  pod 'CapacitorVoiceRecorder', :path => '../../../node_modules/.pnpm/capacitor-voice-recorder@5.0.0_@capacitor+core@5.0.3/node_modules/capacitor-voice-recorder'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
